### ISSUE TITLE
Transfer_token function hasn't finish yet

### ISSUE THREAD

**Issue by xcircle** [arxanchain/wallet-sdk-java#4]
Transfer_token function has so many problem and I think It's just a copy of Issue_token function.
I don't think It's gonna work at all.
em.:    The 'http://API IP地址:9143/wallet-ng/v1/transaction/tokens/transfer/prepare' response is defferent from the other interface which don't have a 'txs' JSONObject.

**Comment by ivy-dong** [comment]
see this：http://chain.arxanfintech.com/infocenter/html/development/wallet.html#id24
URL: http://API IP地址:9143/wallet-ng/v1/transaction/assets/transfer/prepare
response: 交易成功返回值为:
```json

{
    "ErrCode": 0,
    "Payload": "payload string"
}
Payload field is the string marshaled from following JSON object:
[
    {
        "version": 1,
        "timestamp": {
            "time": {
                "seconds": 1524901510,
                "nanos": 312840217
            }
        },
        "txin": [
            {
                "ix": 1,
                "sourceHash": "\331\177\014\020\323S\205Y\361C\330\314D\010\265\033\361\212\217\350#\tE\261\n\010cX\026\333\310\237"
            }
        ],
        "txout": [
            {
                "cTokenId": "1f38a7a1-2c79-465e-a4c0-0038e25c7edg",
                "cType": 2,
                "value": 1,
                "addr": "did:axn:21tDAKCERh95uGgKbJNHYp",
                "until": -1,
                "script": "BgBkNjdmN2VkNGU5M2NhMzk1MmM4NDgzZGNlN2Y4YTExZmRmOTEyNmU2ZTU2NWMzNzk3MTA1NjkzMWRiMjBkZjEyBgBkNjdmN2VkNGU5M2NhMzk1MmM4NDgzZGNlN2Y4YTExZmRmOTEyNmU2ZTU2NWMzNzk3MTA1NjkzMWRiMjBkZjEyBgBkNjdmN2VkNGU5M2NhMzk1MmM4NDgzZGNlN2Y4YTExZmRmOTEyNmU2ZTU2NWMzNzk3MTA1NjkzMWRiMjBkZjEy"
            }
        ],
        "txType": 1,
        "founder": "did:axn:8uQhQMGzWxR8vw5P3UWH1j"
    }
]
```

**Comment by xcircle** [comment]
What I want is transfer token, not assets.

**Comment by ivy-dong** [comment]
http://chain.arxanfintech.com/infocenter/html/development/wallet.html#id22
transfer token just above the transfer assets.

**Comment by xcircle** [comment]
I know, I already see docs,my question is about the Java sdk...you could run a test on the function Wallet.transferToken.I've go through the source and it didn't match the logic.

**Comment by ivy-dong** [comment]
code is right, and after test.
If you see error, plz copy the error message here.
I don't know what problem you have.

**Comment by xcircle** [comment]
can not cast to JSONObject.
![default](https://user-images.githubusercontent.com/5899906/43750477-31db8978-9a2b-11e8-902b-b9c75169e2b9.png)
see there the response of the interface that you mention don't hava a txs item there.
so it goes wrong.
Have you update your code to maven repository?

**Comment by xcircle** [comment]
here's my payload:
{\"from\": \"did:axn:f81479a4-70cd-4932-82de-c070a4085776\", \"to\": \"did:axn:cdeaf69b-9400-4f69-95ad-d67c71b59f0e\", \"tokens\": [{\"token_id\": \"ff2215e66098cdaf3c90fbb7b6b9a92872f94ee99bc403ca1c98b3b28d429585\", \"amount\": 37}],\"fee\":{}}

**Comment by ivy-dong** [comment]
what version you use

**Comment by xcircle** [comment]
2.0.1b

**Comment by ivy-dong** [comment]
show me the complete error msg “ issue ctoken proposal failed ”  +`response` .
I think your response just like:
{"ErrCode":400,"ErrMessage":"transferring requires assets to be transfered","Method":"","Payload":null}
so have no txs.

**Comment by xcircle** [comment]
no,It didn't even go there.
![default](https://user-images.githubusercontent.com/5899906/43752421-7a50b9aa-9a33-11e8-8860-a0f96d9185da.png)
the one before it just throw a Exception.
Payload isn't a JSONObject, It's a JSONArray
It's not error message ether,It's like 
{
	"ErrCode": 0,
	"ErrMessage": "",
	"Method": "",
	"Payload": "[{
	"version": 1,
	"timestamp": {
		"time": {
			"seconds": 1533440585,
			"nanos": 128265075
		}
	},
	"txin": [{
		"sourceHash": "AWi/3PKdqlJ4hvNImszL4caZvHDHKl7IISuU530egJw="
	}],
	"txout": [{
		"cTokenId": "ff2215e66098cdaf3c90fbb7b6b9a92872f94ee99bc403ca1c98b3b28d429585",
		"cType": 1,
		"value": 37,
		"addr": "did:axn:cdeaf69b-9400-4f69-95ad-d67c71b59f0e",
		"until": -1,
		"script": "eyJwdWJsaWNLZXkiOiJ6K25aVWRyYkFqYWJxcnpOcUF1ZzAzcXYrVHo4QUR3MGZmMmhIT1BCanRjPSJ9"
	},
	{
		"cTokenId": "ff2215e66098cdaf3c90fbb7b6b9a92872f94ee99bc403ca1c98b3b28d429585",
		"cType": 1,
		"value": 1200,
		"addr": "did:axn:f81479a4-70cd-4932-82de-c070a4085776",
		"until": -1,
		"script": "eyJwdWJsaWNLZXkiOiJpTTdGV0pySDltbDZtdE90NjZlTGZubXY5VlorbE95ZXMzM3BQVFdkb0xJPSJ9"
	}],
	"txType": 1,
	"founder": "did:axn:f81479a4-70cd-4932-82de-c070a4085776"
}]"
}

**Comment by xcircle** [comment]
Miss?What's wrong,It's been 2 weeks...

**Comment by ivy-dong** [comment]
will fixed in next pull request.
